import Head from 'next/head'
import Image from 'next/image'
import Contact from './components/contact/contact'
import Menu from './components/menu'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className='grid grid-cols-3 min-h-screen'>

      {/*Menu*/}  
      <Menu className='col-span-1' />
      
      {/*Panel*/}
      <Contact className='col-span-2'/>

      
    </main>


    </div>
  )
}
